name: Deploy to Firebase Hosting on Merge
on:
  push:
    branches:
      - main  # or master, depending on your branch name
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_EVIDENCETOIMPACT_92322 }}
          channelId: live # This tells Firebase to update the actual site
          projectId: evidencetoimpact-92322